// -----------------------------------------------------------------------
// <copyright file="ControllerUiEventsAppleTvHint.cs" company="Vmr.Sdl">
// Copyright (c) Vmr.Sdl. All rights reserved.
// Licensed under the MIT license.
// See LICENSE.md for more information.
// </copyright>
// -----------------------------------------------------------------------

using Vmr.Sdl.NativeImports;

namespace Vmr.Sdl.Hints;

/// <summary>A variable controlling whether controllers used with the Apple TV generate UI events.</summary>
/// <remarks>
/// <para>When UI events are generated by controller input, the app will be backgrounded when the Apple TV remote's menu button is pressed, and when the pause or B buttons on gamepads are pressed.</para>
/// <para>More information about properly making use of controllers for the Apple TV can be found here: <see href="https://developer.apple.com/tvos/human-interface-guidelines/remote-and-controllers/"/>.</para>
/// <para>You can set this hint through the environment variable "SDL_APPLE_TV_CONTROLLER_UI_EVENTS" with the values "1" to enable or "0" to disable.</para>
/// </remarks>
public sealed class ControllerUiEventsAppleTvHint : HintBase
{
    private const string Hint = "SDL_APPLE_TV_CONTROLLER_UI_EVENTS";

    /// <summary>Gets or sets a value indicating whether the hint is enabled or not.</summary>
    /// <remarks>
    /// The variable can be set to the following values:
    /// <list type="bullet">
    /// <item><see langword="true"/> (Default): Controller input does not generate UI events.</item>
    /// <item><see langword="false"/>: Controller input generates UI events.</item>
    /// </list>
    /// This hint can be set any time.
    /// </remarks>
    public static bool Value
    {
        get => NativeSdl.GetHintBoolean(Hint, defaultValue: true);
        set => NativeSdl.SetHint(Hint, value ? "1" : "0");
    }

    /// <summary>Sets the hint with the given priority.</summary>
    /// <param name="priority">The priority of the hint.</param>
    /// <param name="value">The value of the hint.</param>
    public static void Set(HintPriority priority, bool value) => SetWithPriority(Hint, value ? "1" : "0", priority);

    /// <summary>Adds a callback to the hint.</summary>
    /// <param name="callback">The callback to add.</param>
    /// <remarks>For safety reasons, only ONE (1) callback will be active at a time, the last one. Adding new callbacks while not removing the old one, will result in the automatic removal of the previous one.</remarks>
    /// <seealso cref="RemoveCallback"/>
    public static void AddCallback(HintUpdated callback) => AddCallback(Hint, callback);

    /// <summary>Removes the callback from the hint.</summary>
    /// <seealso cref="AddCallback"/>
    public static void RemoveCallback() => RemoveCallback(Hint);
}
